services:

    _defaults:
        autowire: true
        autoconfigure: true

    Mustakrakishe\ChainCommandBundle\:
        resource: '../src/'

    Mustakrakishe\ChainCommandBundle\Repository\ChainRepository:
        arguments: 
            $chains: '%mustakrakishe_chain_command.chains%'

    mustakrakishe_chain_command.util.formatter:
        class: Mustakrakishe\ChainCommandBundle\Util\Formatter

    Mustakrakishe\ChainCommandBundle\Service\LoggingService:
        $logger: '@monolog.logger.chain-command'
