services:

    _defaults:
        autowire: true
        autoconfigure: true

    Mustakrakishe\ChainCommandBundle\:
        resource: '../src/'

    Mustakrakishe\ChainCommandBundle\Repository\ChainRepository:
        arguments: 
            $chains: '%mustakrakishe_chain_command.chains%'
